### ISSUE TITLE
Node.js compatibility

### ISSUE THREAD

**Issue by novemberborn** [remerge/micro-http-client#3]
Hey! This is a neat library for building on top of `fetch`. I ran into some challenges and I was wondering about the maintainers' thoughts on them. For the time being I'm using a [fork](https://github.com/remerge/micro-http-client/compare/master...novemberborn:no-transpilation), but my changes are probably unnecessarily extreme.

While the code I'm writing is client-only, I'm still hoping to test it in a Node.js environment. This means I need to be able to provide a `fetch` implementation, and `micro-http-client` shouldn't access any globals directly. You can see my approach in https://github.com/novemberborn/micro-http-client/commit/ce7653d866c4ccd53c8eb5e3545a40a2e0f68dd8 — would you take this as a feature enhancement?

Since https://github.com/remerge/micro-http-client/commit/88d827652a9532f8a828b4128bcc18010e5ce9fd there is an implicit dependency on `regeneratorRuntime` when loading in Node.js. Given the young age of this project, perhaps it should target Node.js 8 and not transpile `async`/`await`? Or otherwise the compilation should be changed so it doesn't need `regeneratorRuntime`, or so that it includes it.

Thanks!

**Comment by wmadden** [comment]
> While the code I'm writing is client-only, I'm still hoping to test it in a Node.js environment. This means I need to be able to provide a fetch implementation, and micro-http-client shouldn't access any globals directly. You can see my approach in novemberborn/micro-http-client@ce7653d — would you take this as a feature enhancement?

Hi @novemberborn, could you give me a bit more information about how you're using this on Node? Why is it important that `micro-http-client` doesn't access the global `fetch` directly, and how is it better to do it through the `globalRef` in your fork? That appears to be equivalent to the current implementation.

The library is deliberately agnostic of its environment, so it should run on Node as well as in the browser. In fact, the tests run in Node already (via Jest), and I add a mock `fetch` method to the environment [here](https://github.com/remerge/micro-http-client/blob/master/src/createFetch.test.js#L3-L13).

> Since 88d8276 there is an implicit dependency on regeneratorRuntime when loading in Node.js. Given the young age of this project, perhaps it should target Node.js 8 and not transpile async/await? Or otherwise the compilation should be changed so it doesn't need regeneratorRuntime, or so that it includes it.

Browsers are the compile target, not Node, so targeting Node 8 (or any other version) doesn't make much sense. However, I agree that including an entire regenerator runtime is a bit stupid for such a small library; I might revert the implementation to just use promises, which I suspect would reduce the size of the output considerably.

The final published module includes the browser-transpiled output as well as the original source, so if you want to import the _untranspiled_ source, you should be able to `require('micro-http-client/src/main')` or something along those lines, although I haven't tested it myself.

**Comment by novemberborn** [comment]
> Hi @novemberborn, could you give me a bit more information about how you're using this on Node? Why is it important that micro-http-client doesn't access the global fetch directly, and how is it better to do it through the globalRef in your fork? That appears to be equivalent to the current implementation.

I'm requiring a module which ends up requiring creating a fetch client. This crashes because there is no global `fetch`. The first change is to make it so a `fetch` implementation can be provided. Presumably we'd still want it to default to the global `fetch`. Hence `globalRef`, which makes it so that accessing the global `fetch` happens through a property. This does not cause a `ReferenceError` if `fetch` is unavailable.

With `regenerator-runtime` and other `micro-http-client` installed, run:

```console
$ node -r regenerator-runtime/runtime -e "require('micro-http-client').createFetch({})"
/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.eZwvdMVoI3/fetch/node_modules/micro-http-client/dist/main.js:101
  return localFetch.bind(null, fetch, requestReducers, responseReducers);
                               ^

ReferenceError: fetch is not defined
    at Object.createFetch (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.eZwvdMVoI3/fetch/node_modules/micro-http-client/dist/main.js:101:32)
    at [eval]:1:30
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:598:3
```

> The library is deliberately agnostic of its environment, so it should run on Node as well as in the browser. In fact, the tests run in Node already (via Jest), and I add a mock fetch method to the environment here.

My preference is to not to mock the global environment when running tests. This also means that the library can't easily be used as a dependency in Node.js, since it requires a globally polyfilled `fetch()` implementation.



> I might revert the implementation to just use promises, which I suspect would reduce the size of the output considerably.

👍
